import type {
  User,
  Agent,
  Client,
  Recommendation,
  DashboardMetrics,
  WhatsAppConnection,
  Settings,
  ReferredClient,
  TimelineEvent,
  FollowUpCampaign,
} from "@/types"

export const mockUser: User = {
  id: "1",
  email: "demo@highfunnel.com",
  name: "Maria Silva",
  companyName: "High Funnel",
  createdAt: new Date("2024-01-15"),
}

export const mockAgents: Agent[] = [
  {
    id: "1",
    userId: "1",
    name: "Agente de Recomendacoes Premium",
    companyName: "High Funnel",
    toneOfVoice: "professional",
    messageToClient:
      "Ola {nome_cliente}! Tudo bem? Aqui e da {empresa}. Voce conhece alguem que poderia se beneficiar dos nossos servicos? Para cada recomendacao, preparamos um presente especial para voce!",
    messageGiftToRecommender:
      "Parabens {nome_cliente}! Voce atingiu {quantidade} recomendacoes e ganhou: {bonus}. Seu presente esta pronto para ser enviado!",
    messageToReferred:
      "Ola {nome_recomendado}! O(a) {nome_cliente} mencionou que voce poderia se interessar pelos servicos da {empresa}. Temos uma oferta especial para voce: {oferta}. Podemos conversar?",
    messageGiftToReferred:
      "Que bom ter voce com a gente, {nome_recomendado}! Como presente de boas-vindas, preparamos: {bonus_recomendado}. Aproveite!",
    recommendationRule: "Solicitar recomendacao de empresas ou profissionais que possam precisar de automacao",
    offerDescription: "15% de desconto na primeira mensalidade",
    gamificationRules: [
      { id: "1", leadsRequired: 5, bonusDescription: "E-book exclusivo de Automacao com IA", bonusMultiplier: 1 },
      { id: "2", leadsRequired: 10, bonusDescription: "Consultoria gratuita de 30 min", bonusMultiplier: 2 },
      { id: "3", leadsRequired: 15, bonusDescription: "1 mes gratis do plano Premium", bonusMultiplier: 3 },
    ],
    followUpMessages: [
      {
        id: "1",
        name: "Lembrete inicial",
        trigger: "no_recommendations_sent",
        delayHours: 24,
        message: "Ola {nome_cliente}! Vi que voce ainda nao enviou suas recomendacoes. Lembre-se: a cada 5 recomendacoes voce ganha um presente especial!",
        isActive: true,
      },
      {
        id: "2",
        name: "Quase la",
        trigger: "partial_recommendations",
        delayHours: 48,
        message: "Ola {nome_cliente}! Falta apenas {faltam} recomendacao(oes) para voce ganhar seu presente. Ele ja esta pronto aqui, posso enviar?",
        isActive: true,
      },
      {
        id: "3",
        name: "Agradecimento",
        trigger: "post_recommendation",
        delayHours: 1,
        message: "Obrigado pela recomendacao, {nome_cliente}! Ja entramos em contato com {nome_recomendado}. Continue recomendando para ganhar ainda mais premios!",
        isActive: true,
      },
    ],
    status: "active",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    userId: "1",
    name: "Agente Casual - Recomendacoes",
    companyName: "High Funnel",
    toneOfVoice: "friendly",
    messageToClient:
      "E ai {nome_cliente}! Beleza? A gente ta com uma campanha aqui na {empresa}. Indica uns amigos pra gente que voce ganha uns presentes maneiros!",
    messageGiftToRecommender:
      "Ae {nome_cliente}! Suas recomendacoes tao bombando! Voce ganhou: {bonus}. Parabens!",
    messageToReferred:
      "Fala {nome_recomendado}! Sou da {empresa}, o(a) {nome_cliente} te recomendou pra gente. Temos algo especial: {oferta}. Bora trocar uma ideia?",
    messageGiftToReferred:
      "Bem-vindo(a) {nome_recomendado}! De presente pra voce: {bonus_recomendado}. Aproveita!",
    recommendationRule: "Pedir recomendacoes de forma descontraida",
    offerDescription: "Primeira consultoria gratuita",
    gamificationRules: [
      { id: "1", leadsRequired: 3, bonusDescription: "Template de automacao pronto", bonusMultiplier: 1 },
      { id: "2", leadsRequired: 7, bonusDescription: "Acesso VIP por 1 semana", bonusMultiplier: 2 },
    ],
    followUpMessages: [],
    status: "inactive",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-25"),
  },
]

export const mockClients: Client[] = [
  {
    id: "1",
    userId: "1",
    name: "Joao Santos",
    phone: "+5511987654321",
    email: "joao@example.com",
    status: "recommendations_completed",
    recommendationCount: 3,
    lastRecommendationDate: new Date("2024-01-20"),
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    userId: "1",
    name: "Ana Costa",
    phone: "+5511876543210",
    email: "ana@example.com",
    status: "collecting_recommendations",
    recommendationCount: 2,
    lastRecommendationDate: new Date("2024-01-22"),
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "3",
    userId: "1",
    name: "Carlos Oliveira",
    phone: "+5511765432109",
    status: "not_started",
    recommendationCount: 0,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "4",
    userId: "1",
    name: "Patricia Lima",
    phone: "+5511654321098",
    email: "patricia@example.com",
    status: "not_started",
    recommendationCount: 0,
    createdAt: new Date("2024-01-14"),
  },
]

export const mockRecommendations: Recommendation[] = [
  {
    id: "1",
    agentId: "1",
    clientId: "1",
    referredClientName: "Pedro Almeida",
    referredClientPhone: "+5511999888777",
    status: "converted",
    messagesSent: 5,
    lastMessageDate: new Date("2024-01-22"),
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    agentId: "1",
    clientId: "2",
    referredClientName: "Mariana Souza",
    referredClientPhone: "+5511888777666",
    status: "accepted",
    messagesSent: 3,
    lastMessageDate: new Date("2024-01-23"),
    createdAt: new Date("2024-01-22"),
  },
  {
    id: "3",
    agentId: "1",
    clientId: "1",
    referredClientName: "Roberto Silva",
    status: "pending",
    messagesSent: 1,
    lastMessageDate: new Date("2024-01-24"),
    createdAt: new Date("2024-01-24"),
  },
]

export const mockMetrics: DashboardMetrics = {
  totalClients: 127,
  totalRecommendations: 48,
  totalReferredClients: 35,
  conversions: 23,
  conversionRate: 65.7,
  activeAgents: 1,
}

export const mockWhatsAppConnection: WhatsAppConnection = {
  id: "1",
  userId: "1",
  status: "disconnected",
  phoneNumber: undefined,
  qrCode: undefined,
  connectedAt: undefined,
  lastActivityAt: undefined,
}

export const mockSettings: Settings = {
  userId: "1",
  companyName: "High Funnel",
  companyDescription: "Plataforma de recomendacoes inteligentes com IA que conecta empresas aos melhores leads atraves de recomendacoes de clientes satisfeitos.",
  companyContext: "Atuamos no segmento B2B de tecnologia e automacao. Nossos clientes sao empresas de medio porte que buscam escalar suas vendas atraves de recomendacoes qualificadas. O tom ideal e profissional mas acessivel.",
  language: "pt-BR",
  webhookUrl: "https://api.highfunnel.com/webhook",
  notificationsEnabled: true,
}

export const mockReferredClients: ReferredClient[] = [
  {
    id: "1",
    userId: "1",
    name: "Pedro Almeida",
    phone: "+5511999888777",
    sourceClientId: "1",
    sourceClientName: "Joao Santos",
    agentId: "1",
    status: "converted",
    messagesSent: 5,
    lastContactDate: new Date("2024-01-22"),
    offerSentDate: new Date("2024-01-21"),
    convertedDate: new Date("2024-01-23"),
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    userId: "1",
    name: "Mariana Souza",
    phone: "+5511888777666",
    sourceClientId: "1",
    sourceClientName: "Joao Santos",
    agentId: "1",
    status: "offer_sent",
    messagesSent: 3,
    lastContactDate: new Date("2024-01-23"),
    offerSentDate: new Date("2024-01-23"),
    createdAt: new Date("2024-01-22"),
  },
  {
    id: "3",
    userId: "1",
    name: "Roberto Silva",
    phone: "+5511777666555",
    sourceClientId: "1",
    sourceClientName: "Joao Santos",
    agentId: "1",
    status: "contact_initiated",
    messagesSent: 2,
    lastContactDate: new Date("2024-01-24"),
    createdAt: new Date("2024-01-24"),
  },
  {
    id: "4",
    userId: "1",
    name: "Fernanda Costa",
    phone: "+5511666555444",
    sourceClientId: "2",
    sourceClientName: "Ana Costa",
    agentId: "1",
    status: "new",
    messagesSent: 0,
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "5",
    userId: "1",
    name: "Lucas Martins",
    phone: "+5511555444333",
    sourceClientId: "2",
    sourceClientName: "Ana Costa",
    agentId: "1",
    status: "new",
    messagesSent: 0,
    createdAt: new Date("2024-01-25"),
  },
]

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: "1",
    clientId: "1",
    agentId: "1",
    type: "message_sent",
    description: "Mensagem de recomendacao enviada para Joao Santos via WhatsApp",
    createdAt: new Date("2024-01-19T10:30:00"),
  },
  {
    id: "2",
    clientId: "1",
    agentId: "1",
    type: "recommendation_received",
    description: "Joao Santos recomendou Pedro Almeida",
    createdAt: new Date("2024-01-20T14:00:00"),
  },
  {
    id: "3",
    clientId: "1",
    referredClientId: "1",
    agentId: "1",
    type: "message_sent",
    description: "Mensagem enviada para Pedro Almeida (recomendado)",
    createdAt: new Date("2024-01-20T14:30:00"),
  },
  {
    id: "4",
    clientId: "1",
    agentId: "1",
    type: "recommendation_received",
    description: "Joao Santos recomendou Mariana Souza",
    createdAt: new Date("2024-01-21T09:00:00"),
  },
  {
    id: "5",
    clientId: "1",
    agentId: "1",
    type: "gift_sent",
    description: "Presente enviado para Joao Santos: E-book exclusivo (3 recomendacoes)",
    createdAt: new Date("2024-01-21T10:00:00"),
  },
  {
    id: "6",
    clientId: "1",
    referredClientId: "1",
    agentId: "1",
    type: "offer_sent",
    description: "Oferta enviada para Pedro Almeida: 15% desconto",
    createdAt: new Date("2024-01-21T11:00:00"),
  },
  {
    id: "7",
    clientId: "1",
    referredClientId: "1",
    agentId: "1",
    type: "status_changed",
    description: "Pedro Almeida converteu - novo cliente!",
    createdAt: new Date("2024-01-23T16:00:00"),
  },
  {
    id: "8",
    clientId: "2",
    agentId: "1",
    type: "message_sent",
    description: "Mensagem de recomendacao enviada para Ana Costa via WhatsApp",
    createdAt: new Date("2024-01-22T10:30:00"),
  },
  {
    id: "9",
    clientId: "2",
    agentId: "1",
    type: "recommendation_received",
    description: "Ana Costa recomendou Fernanda Costa e Lucas Martins",
    createdAt: new Date("2024-01-25T11:15:00"),
  },
  {
    id: "10",
    clientId: "2",
    agentId: "1",
    type: "follow_up_sent",
    description: "Follow-up enviado para Ana Costa: Falta 3 recomendacoes para o presente!",
    createdAt: new Date("2024-01-26T09:00:00"),
  },
]

export const mockFollowUpCampaigns: FollowUpCampaign[] = [
  {
    id: "1",
    name: "Reativacao de clientes inativos",
    message: "Ola {nome_cliente}! Faz tempo que nao conversamos. Que tal recomendar alguem e ganhar um presente especial? Temos novas ofertas esperando por voce!",
    targetAudience: "no_recommendations",
    status: "sent",
    sentAt: new Date("2024-01-20T10:00:00"),
    recipientCount: 45,
    openRate: 72.5,
    createdAt: new Date("2024-01-19"),
  },
  {
    id: "2",
    name: "Promocao de Janeiro",
    message: "Ola {nome_cliente}! Este mes temos uma promocao exclusiva: recomende 3 amigos e ganhe 1 mes gratis! Aproveite, a promocao vai ate o final do mes.",
    targetAudience: "all_clients",
    status: "scheduled",
    scheduledAt: new Date("2024-02-01T09:00:00"),
    recipientCount: 127,
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "3",
    name: "Lembrete de recomendacao parcial",
    message: "Ola {nome_cliente}! Voce ja recomendou {quantidade} amigos, falta pouco para ganhar seu proximo presente! Envie mais {faltam} recomendacoes.",
    targetAudience: "partial_recommendations",
    status: "draft",
    recipientCount: 18,
    createdAt: new Date("2024-01-26"),
  },
]
